query visions(
  $individualId: ID
  $cycleId: ID
  $fetchIndividualId: ID!
  $fetchIndividualDetails: Boolean = false
  $level: VisionFilterLevel
) {
  individual(id: $fetchIndividualId) @include(if: $fetchIndividualDetails) {
    fullname
  }
  cycles(orderBy: [{ field: "from", direction: "desc" }]) {
    nodes {
      id
      title
    }
  }
  visions(
    individualId: $individualId
    cycleId: $cycleId
    level: $level
    orderBy: [{ field: "validFrom", direction: "desc" }]
  ) {
    nodes {
      id
      visionType {
        id
        title
      }
      documentId
      documentUrl
      hasContent
      date
      validFrom
      validTo
      description
      cycleId
      individualId
      organizationId
      cycle {
        title
        from
        to
      }
    }
  }
}
