fragment AdviceFragment on Advice {
  cycleId
  id
  isAnalyzed
  isActivityAnalyzed
  isVisionAnalyzed
  result
  visionSummary
  activitySummary
  analyzedAt
  activitiesTotal
  analyzedActivitiesTotal
  visionsTotal
}
