query coachIndividual($id: ID!) {
  individual(id: $id) {
    ...IndividualFragment
    activeCycles {
      nodes {
        ...CycleFragment
      }
    }
  }
  adviceList(individualId: $id) {
    nodes {
      ...AdviceFragment
    }
  }
}
