mutation GenerateCycleAdvice($individualId: Int!, $cycleId: Int!) {
  generateCycleAdvice(
    input: { individualId: $individualId, cycleId: $cycleId }
  ) {
    advice {
      ...AdviceFragment
    }
  }
}
