query individualVisions($individualId: ID!, $cycleId: ID) {
  individual(id: $individualId) {
    fullname
  }
  cycles(orderBy: [{ field: "from", direction: "desc" }]) {
    nodes {
      id
      title
    }
  }
  visions(
    individualId: $individualId
    cycleId: $cycleId
    orderBy: [{ field: "date", direction: "desc" }]
  ) {
    nodes {
      id
      visionType {
        id
        title
      }
      documentId
      documentUrl
      hasContent
      date
      validFrom
      validTo
      description
      cycleId
      individualId
      cycle {
        title
        from
        to
      }
    }
  }
}
