fragment OrganizationFragment on Organization {
  id
  name
  owner {
    email
  }
  isPersonal
  isSystem
  githubOrgs
  useSystemGithubToken
  githubToken
  useSystemAiEngine
  systemAiEngineUsedPromptTokens
  systemAiEngineUsedCompletionTokens
  systemAiEngineMaxTokens
  aiEngines {
    nodes {
      id
      type {
        id
        title
      }
      settings
    }
  }
}
