query individuals(
  $managerId: ID
  $fetchManagerId: ID!
  $fetchManagerDetails: Boolean = false
  $isManager: Boolean
) {
  individuals(managerId: $managerId, isManager: $isManager, isActive: true) {
    nodes {
      id
      fullname
      jobTitle
      jobLevelId
      isManager
    }
  }
  managerInfo: individual(id: $fetchManagerId)
    @include(if: $fetchManagerDetails) {
    id
    fullname
    jobTitle
  }
}
