query individualActivities($individualId: ID!, $isAnalyzed: Boolean) {
  individual(id: $individualId) {
    fullname
  }
  activities(
    individualId: $individualId
    isAnalyzed: $isAnalyzed
    orderBy: [{ field: "date", direction: "desc" }]
  ) {
    nodes {
      id
      title
      isAnalyzed
      date
      channelId
      channelActivityUrl
      cycle {
        id
        title
      }
    }
  }
}
