name: Typescript Type Check

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: ./github/actions/setup

      - name: Run tsc
        run: yarn tsc
