fragment VisionFragment on Vision {
  id
  visionTypeId
  visionType {
    title
  }
  documentId
  description
  documentUrl
  content
  cycleId
  individualId
  validFrom
  validTo
  isOrganizational
}
